name: PySE CI

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t transientskp/pyse .
      - name: Run nosetests3
        run: |
          docker run transientskp/pyse nosetests3 --with-coverage --cover-package=sourcefinder
      - name: Run pyse
        run: |
          docker run transientskp/pyse pyse --detection 5 --radius 400 --csv --force-beam  test/data/GRB120422A-120429.fits
